# Application
spring:
  application:
    name: parking-share
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.209.172:3306/wow_test_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: wow
    password: NewL1fe1223..
  data:
    redis:
      host: dbconn.sealosgzg.site
      port: 35471
      database: 0
      username: default
      password: xjcwsdq2
      timeout: 10000ms
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.parking.model.entity.mybatis
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JPA（注释部分原样保留）
# spring:
#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL8Dialect

# JWT
jwt:
  secret: yoursecretkeyxxxxxxyyyyyyzzzzzzyoursecretkeyxxxxxxyyyyyyzzzzzzyoursecretkeyxxxxxxyyyyyyzzzzzz
  expiration: 86400000

# wechat implement
wechat:
  appid: wx1234567890
  secret: abcdef1234567890
  pay:
    app-id: wx1234567890
    mch-id: 1234567890
    mch-serial-no: abcdef1234567890
    notify_url: https://139.224.209.172:8080/api/pay/notify
    private-key-path: https://139.224.209.172:8080/api/pay/notify
    api-v3-key: https://139.224.209.172:8080/api/pay/notify

# ali pay
alipay:
  appid: your_app_id
  private-key: your_private_key
  public-key: alipay_public_key
  server-url: https://openapi.alipay.com/gateway.do
  notify-url: https://139.224.209.172:8080/api/alipay/notify
  return-url: https://139.224.209.172:8080/pay/result
  sign-type: RSA2
  charset: UTF-8
  format: json

aliyun:
  sms:
    access-key-id: LTAI5tL3BJLgNkvHZcKWa2VP
    access-key-secret: tgCGGmNklcb3EFu4gtoACM1EbeOFen
    sign-name: wow
    template-code: SMS_154950909

# File Upload
upload:
  upload-path: ./uploads
  allow-types: jpg,jpeg,png,gif
  max-size: 10
  use-cloud: false
  cloud-storage:
    access-key: your_access_key_id
    secret-key: your_access_key_secret
    bucket: your-bucket-name
    domain: aliyuncs.com
    region: cn-hangzhou
    endpoint: oss-cn-hangzhou.aliyuncs.com
    base-path: images
    custom-domain: img.yourdomain.com
    use-https: true
    private-bucket: false
    url-expire: 3600

# Logging
logging:
  level:
    root: INFO
    com.parking: DEBUG

# Encryption
encrypt:
  aes:
    key: your16byteseckey # 必须是16位